import { Injectable, Inject } from '@nestjs/common';
import { Unity } from '../entities/unity.entity';
import { UnityRepositoryInterface } from '../repositories/unity.repository.interface';
import { CreateUnityDto } from '../dto/create-unity.dto';

@Injectable()
export class CreateUnityUseCase {
  constructor(
    @Inject('UnityRepositoryInterface')
    private readonly unityRepository: UnityRepositoryInterface,
  ) {}

  async execute(input: CreateUnityDto): Promise<void> {
    const unity = new Unity(
      '', // ID will be generated by repository
      input.name,
      input.address,
      null, // logoUrl will be handled separately if needed
    );

    await this.unityRepository.create(unity);
  }
}
