import { Injectable, Inject } from '@nestjs/common';
import { Meeting } from '../entities/meeting.entity';
import { MeetingRepositoryInterface } from '../repositories/meeting.repository.interface';
import { CreateMeetingDto } from '../dto/create-meeting.dto';

@Injectable()
export class CreateMeetingUseCase {
  constructor(
    @Inject('MeetingRepositoryInterface')
    private readonly meetingRepository: MeetingRepositoryInterface,
  ) {}

  async execute(input: CreateMeetingDto): Promise<Meeting> {
    const meeting = new Meeting(
      '', // ID will be generated by repository
      input.title,
      input.description,
      '', // Unity name will be resolved from unityId
      input.startDate,
      input.location,
      input.status,
    );

    return await this.meetingRepository.create(meeting);
  }
}
